### ISSUE TITLE
Pass in specific pytest command?

### ISSUE THREAD

**Issue by Freddie-Pike** [coroo/pytest-coverage-commentator#107]
Is it possible to pass in a specifc pytest command? I'm running python in a docker environment so I need to pass in a custom command.

**Comment by MishaKav** [comment]
Have the same issue. Found solution on similar GitHub Action: [Pytest Coverage Comment](https://github.com/marketplace/actions/pytest-coverage-comment)
The bottom example in readme shows how to use it when you running the pytest inside docker:

```
- name: Run unit tests (pytest)
  run: |
    docker run -v /tmp:/tmp $IMAGE_TAG python3 -m pytest --cov-report=term-missing:skip-covered --junitxml=/tmp/pytest.xml --cov=src tests/ | tee /tmp/pytest-coverage.txt

- name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@v1.0
  with:
    pytest-coverage-path: /tmp/pytest-coverage.txt
    junitxml-path: /tmp/pytest.xml
```
