### ISSUE TITLE
Use plugin behind proxy?

### ISSUE THREAD

**Issue by nbahar-intel** [coroo/pytest-coverage-commentator#133]
Hi,
We have a HTTP and HTTPS proxy we configure to reach to GitHub.com

Unfortunately I've tried using the plugin but it seems like I encounter API connection issues:

Error: Workflow failed! request to https://api.github.com/repos/.../issues/1163/comments failed, reason: tunneling socket could not be established, statusCode=407

I've tried settings HTTP_PROXY and HTTPS_PROXY environment variables but it did not help.

```
    - name: Pytest Coverage Commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
       pytest-coverage: pytest-coverage.txt
      env:
        HTTP_PROXY: http://proxyurl
        HTTPS_PROXY: http://proxyurl
```

**Comment by nbahar-intel** [comment]
Seems like I had to use lower-case environment variables

Fixed to
```
    - name: Pytest Coverage Commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
       pytest-coverage: pytest-coverage.txt
      env:
        http_proxy: http://proxyurl
        https_proxy: http://proxyurl
```
