### ISSUE TITLE
**Workflow failed! Resource not accessible by integration** for the first time

### ISSUE THREAD

**Issue by rabinadk1** [coroo/pytest-coverage-commentator#153]
I get the resource not accessible error for every first time the action is run. When I re-run it, it works well. It has become annoying to rerun it every time for each PR.

I have attached the workflow file below.

```yaml
# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Comment Backend Coverage Report

on:
  pull_request:
    branches: [ main ]
    paths:
        - 'server/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: server/

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: server/
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest-cov
    - name: Build coverage file
      run: |
        pytest --cov=app test | tee ../pytest-coverage.txt
      env:
        JWT_SECRET_KEY: ${{ github.sha }}
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
```
