### ISSUE TITLE
Workflow failed! Resource not accessible by integration

### ISSUE THREAD

**Issue by krkeegan** [coroo/pytest-coverage-commentator#30]
I am getting the error Workflow failed! Resource not accessible by integration

I am using the following workflow.  Everything works fine if I comment out the Comment Coverage step.

```
name: Linting and Pytest

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Lint with flake8 exit on errors
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
      run: |
        # Skips creating coverage stats for covered items
        pytest --cache-clear --cov-report term:skip-covered --cov=app tests/ | tee pytest-coverage.txt
     - name: Comment coverage
       uses: coroo/pytest-coverage-commentator@v1.0.2
       with:
         pytest-coverage: pytest-coverage.txt
```
