### ISSUE TITLE
Reporting coverage for matrix build overwrites post

### ISSUE THREAD

**Issue by adborden** [coroo/pytest-coverage-commentator#99]
I'm using a matrix build to test multiple versions of Python and frameworks (CKAN). In each case, I'd like to see a report for the test coverage (each in its own PR comment is fine) for each build. However, the action currently overwrites the comment with the last matrix build.

Example workflow with matrix builds:
```yaml
# .github/workflows/test.yml
jobs:
  test:
    needs: lint
    strategy:
      matrix:
        ckan-version: [2.9, 2.8]  # 2.9 implies py3
      fail-fast: false
  steps:
    - name: Run tests
      run: pytest --ckan-ini=test.ini --cov=ckanext.datagovtheme --disable-warnings ckanext/datagovtheme/tests | tee pytest-coverage.txt
    - name: Report test coverage
      if: ${{ always() }}
      uses: coroo/pytest-coverage-commentator@v1.0.2
```

**Comment by MishaKav** [comment]
Have the same issue. Found solution on similar GitHub Action: [Pytest Coverage Comment](https://github.com/marketplace/actions/pytest-coverage-comment)
It has an option to `createNewComment` each time, and not replace the same one.

```yaml
- name: Pytest coverage comment
    uses: MishaKav/pytest-coverage-comment@v1.0
    with:
      pytest-coverage-path: ./pytest-coverage.txt
      create-new-comment: true
      title: "CKAN ${{ matrix.ckan-version }}"
      badge-title: "CKAN ${{ matrix.ckan-version }}"
```

![image](https://user-images.githubusercontent.com/289035/120553884-b411aa00-c401-11eb-94e5-a4bee3fa83c3.png)
